#!/bin/bash

set -xe

pwd
env

cf api $CF_API --skip-ssl-validation

cf login -u $CF_USER -p $CF_PWD -o "$CF_ORG" -s "$CF_SPACE"

cf apps

cf routes

# Map route to "next" app
export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
echo "Mapping main app route to point to $NEXT_APP_COLOR instance"
cf map-route $CF_APP-$NEXT_APP_COLOR $CF_APP_DOMAIN --hostname $CF_APP

# Delete old App
export OLD_APP_COLOR=$(cat ./current-app-info/current-app.txt)
cf delete $CF_APP-$OLD_APP_COLOR -f


echo "Apps and Routes updated"
cf apps
cf routes
